# Generated by Django 3.0.4 on 2020-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_cafes_foto_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafes',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
