# Generated by Django 3.0.4 on 2020-04-08 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=150)),
                ('foto_usuario', models.ImageField(blank=True, null=True, upload_to='usuario')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
