# Generated by Django 3.0.4 on 2020-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuario'),
        ),
    ]
