# Generated by Django 3.0.4 on 2020-04-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bebidas', '0001_initial'),
        ('chas', '0001_initial'),
        ('cafes', '0001_initial'),
        ('salgados', '0001_initial'),
        ('doces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('bebidas', models.ManyToManyField(to='bebidas.Bebidas')),
                ('cafe', models.ManyToManyField(to='cafes.Cafes')),
                ('chas', models.ManyToManyField(to='chas.Chas')),
                ('doce', models.ManyToManyField(to='doces.Doces')),
                ('salgado', models.ManyToManyField(to='salgados.Salgados')),
            ],
            options={
                'verbose_name': 'CardapioProduto',
                'verbose_name_plural': 'CardapioProdutos',
            },
        ),
    ]
