# Generated by Django 3.0.4 on 2020-04-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0001_initial'),
        ('doces', '0001_initial'),
        ('salgados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.Cafes')),
                ('doce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doces.Doces')),
                ('salgado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salgados.Salgados')),
            ],
        ),
    ]
