# Generated by Django 3.0.4 on 2020-04-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doces', '0001_initial'),
        ('cafes', '0001_initial'),
        ('salgados', '0001_initial'),
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='cafe',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='cafe',
            field=models.ManyToManyField(to='cafes.Cafes'),
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='doce',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='doce',
            field=models.ManyToManyField(to='doces.Doces'),
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='salgado',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='salgado',
            field=models.ManyToManyField(to='salgados.Salgados'),
        ),
    ]
